version: '3.7'
services:
  dev_container:
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace
    build:
      # context: where should docker-compose look for the Dockerfile?
      # i.e. either a path to a directory containing a Dockerfile, or a url to a git repository
      context: ..
      dockerfile: Dockerfile.dev
    env_file: 
      - ../.env
    environment:
      - FLASK_CONFIG=development
      - FLASK_ENV=development
    # Forwards port 0.0.0.0:5003 from the Docker host (e.g. your computer) 
    # to the dev environment container's port 5002
    ports:
      - 0.0.0.0:5003:5002
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - timescaledb_network
networks:
  timescaledb_network:
    external:
      name: timescaledb_network
